# fly.toml app configuration file generated for silent-night-9401 on 2023-08-14>
#
# See https://fly.io/docs/reference/configuration/ for information about how to>
#
app = "silent-night-9401"
primary_region = "sin"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  internal_port = 22
  protocol = "tcp"

  [[services.ports]]
    port = "22"
