# fly.toml app configuration file generated for silent-night-9401 on 2023-08-14>
#
# See https://fly.io/docs/reference/configuration/ for information about how to>
#
app = "silent-night-9401"
primary_region = "sin"

[build]

[[services]]
  internal_port = 22
  protocol = "tcp"

  [[services.ports]]
    port = "22"
